// Generated by CoffeeScript 1.6.3
(function() {
  var $, Bot, BotController;

  $ = jQuery;

  Bot = (function() {
    function Bot() {
      var canvas;
      canvas = document.getElementById('container');
      this.context = canvas.getContext('2d');
      this.x = 1;
      this.y = 1;
      this.faceAngle = 0;
    }

    Bot.prototype.drawBot = function() {
      this.context.clearRect(0, 0, 1500, 1500);
      this.context.lineWidth = 2;
      this.context.strokeStyle = 'green';
      return this.context.strokeRect(this.x, this.y, 2, 1);
    };

    Bot.prototype.strafeRight = function() {
      return this.x++;
    };

    Bot.prototype.strafeLeft = function() {
      return this.x--;
    };

    Bot.prototype.turnRight = function() {
      this.faceAngle += 8;
      if (this.faceAngle >= 360) {
        return this.faceAngle = 0;
      }
    };

    Bot.prototype.turnLeft = function() {
      this.faceAngle -= 8;
      if (this.faceAngle < 0) {
        return this.faceAngle = 359;
      }
    };

    Bot.prototype.forward = function() {
      this.x += Math.cos(this.faceAngle * Math.PI / 180);
      return this.y += Math.sin(this.faceAngle * Math.PI / 180);
    };

    Bot.prototype.backward = function() {
      this.x -= Math.cos(this.faceAngle * Math.PI / 180);
      return this.y -= Math.sin(this.faceAngle * Math.PI / 180);
    };

    return Bot;

  })();

  BotController = (function() {
    function BotController(bot) {
      var forwardTrigger, map;
      map = {};
      forwardTrigger = $.Event('keydown');
      console.log(forwardTrigger);
      forwardTrigger.which = 87;
      $(document).bind('key keydown', function(e) {
        map[e.keyCode] = true;
        return BotController.move(bot, map);
      });
      $(document).bind('key keyup', function(e) {
        map[e.keyCode] = false;
        BotController.move(bot, map);
        if (map[87]) {
          return $(document).trigger(forwardTrigger);
        }
      });
    }

    BotController.move = function(bot, map) {
      console.log(map);
      if (map[69]) {
        bot.strafeRight();
        $.ajax({
          url: "127.0.0.1:8071/motion-control/update",
          data: {
            strafe: 1
          },
          dataType: jsonp
        });
      }
      if (map[81]) {
        bot.strafeLeft();
        $.ajax({
          url: "127.0.0.1:8071/motion-control/update",
          data: {
            strafe: -1
          },
          dataType: jsonp
        });
      }
      if (map[68]) {
        bot.turnRight();
        $.ajax({
          url: "127.0.0.1:8071/motion-control/update",
          data: {
            turn: 1
          },
          dataType: jsonp
        });
      }
      if (map[65]) {
        bot.turnLeft();
        $.ajax({
          url: "127.0.0.1:8071/motion-control/update",
          data: {
            turn: -1
          },
          dataType: jsonp
        });
      }
      if (map[87]) {
        bot.forward();
        $.ajax({
          url: "127.0.0.1:8071/motion-control/update",
          data: {
            forward: 1
          },
          dataType: jsonp
        });
      }
      if (map[83]) {
        bot.backward();
        $.ajax({
          url: "127.0.0.1:8071/motion-control/update",
          data: {
            forward: -1
          },
          dataType: jsonp
        });
      }
      return bot.drawBot();
    };

    return BotController;

  })();

  $(document).ready(function() {
    var bot, botControl;
    bot = new Bot;
    bot.drawBot();
    return botControl = new BotController(bot);
  });

}).call(this);
